version: '3.1'

volumes:
  postgres_db:

services:
  postgres_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER = postgres
      - POSTGRES_PASS = root
      - POSTGRES_DB = postgres
    volumes:
      - postgres_db
    ports:
      - "5432:5432"

  app:
    restart: always
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres_db:5432/postgres'
